<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="myzharbot_passive_sprocket">	
  
  <xacro:macro name="myzharbot_passive_sprocket" params="sprocket_suffix position *joint_pose">
  
    <link name="spr_${sprocket_suffix}">
      <visual>
        <geometry>
          <cylinder length="${passive_sprocket_leght}" radius="${passive_sprocket_radius}"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
    </link>
  
    <joint name="Sprocket_${sprocket_suffix}" type="fixed">
      <parent link="base_link"/>
      <child link="spr_${sprocket_suffix}"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 0 1" rpy="0 0 0"/>      
    </joint>
    
    <transmission name="sprocket_trans_${sprocket_suffix}">
    	<type>transmission_interface/SimpleTransmission</type>
    	<joint name="Sprocket_${sprocket_suffix}">
      		<hardwareInterface>EffortJointInterface</hardwareInterface>
    	</joint>
    	<actuator name="${position}">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
      			<mechanicalReduction>${active_sprocket_radius/passive_sprocket_radius}</mechanicalReduction>
        </actuator>
    </transmission>  
  </xacro:macro>

</robot>
