## USB port
port: /dev/ttyUSB1


##### Calibration ####
### accelerometer
accel_x_min: -261.0
accel_x_max: 252.0
accel_y_min: -263.0
accel_y_max: 261.0
accel_z_min: -165.0
accel_z_max: 324.0

### magnetometer
# standard calibration
magn_x_min: -447.0
magn_x_max: 480.0
magn_y_min: -269.0
magn_y_max: 680.0
magn_z_min: -387.0
magn_z_max: 374.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-19.2327, 206.296, -12.3382]
magn_ellipsoid_transform: [[0.729319, -0.00976591, -0.0241331], [-0.00976591, 0.787807, 0.0915085], [-0.0241331, 0.0915085, 0.957564]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -30.40
gyro_average_offset_y: -83.40
gyro_average_offset_z: 5.40
