motor_0:
  Bridge: 12.0
  CPR: 400
  Enable: 0
  Encoder: 1
  Ratio: 18.3
  Rotation: 1
  emergency: { Bridge_off: 2.0, Slope_time: 1.0, Timeout: 100}
  pid: { Frequency: 1, Kp: 0.05, Ki: 0.2, Kd: 0.45}
motor_1:
  Bridge: 12.0
  CPR: 400
  Enable: 0
  Encoder: 1
  Ratio: 18.3
  Rotation: -1
  emergency: { Bridge_off: 2.0, Slope_time: 1.0, Timeout: 100}
  pid: { Frequency: 1, Kp: 0.05, Ki: 0.2, Kd: 0.45}
