teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.2
  scale_linear_turbo: 0.4
  axis_angular: 0
  scale_angular: 1.0
  enable_button: 0
  enable_turbo_button: 1
joy_node: 
  deadzone: 0.01
  autorepeat_rate: 20
